version: 2

models:
  - name: int_localbike_dataset__best_products
    description: "For each product in each store, this model contains the quantity sold and the total amount earned."
    columns:
      - name: store_product_id
        description: "Primary key, unique identifier for each product in each store: concatenation of store_id and product_id."
        tests:
            - unique
            - not_null
      - name: total_products_sold
        description: "For each product and each store, total quantity of this product sold in this store."
      - name: total_products_sold_amount
        description: "For each product and each store, total amount earned by selling this product in this store."

  - name: int_localbike_dataset__order_items
    description: "This model adds information from stg_localbike_dataset__orders to stg_localbike_dataset__order_items: customer_id and store_id."
    columns:
      - name: order_item_id
        description: "Primary key, unique identifier for each order item."
        tests:
            - unique
            - not_null

  - name: int_localbike_dataset__orders
    description: "This model adds aggregated information from stg_localbike_dataset__order_items to stg_localbike_dataset__orders, including total amount per order."
    columns:
      - name: order_id
        description: "Primary key, unique identifier for each order."
        tests:
            - unique
            - not_null

  - name: int_localbike_dataset_aggregated_stocks
    description: "This model contains aggregated information about stocks in each store."
    columns:
      - name: stock_store_product_id
        description: "Primary key, unique identifier for the stock of each product in each store: generated by concatenating store_id and product_id."
        tests:
            - unique
            - not_null