version: 2

models:
  - name: stg_localbike_dataset__brands
    description: "This model contains information about the brands sold in the Local Bike stores."
    columns:
      - name: brand_id
        description: "Primary key, unique identifier for each brand."
        tests:
            - unique
            - not_null
      - name: brand_name
        description: "Name of the brand."

  - name: stg_localbike_dataset__categories
    description: "This model contains information about the categories of bikes sold in the Local Bike stores."
    columns:
      - name: category_id
        description: "Primary key, unique identifier for each category."
        tests:
            - unique
            - not_null
      - name: category_name
        description: "Name of the category of bikes."

  - name: stg_localbike_dataset__customers
    description: "This model contains customer-related information, including where they live."
    columns:
      - name: customer_id
        description: "Primary key, unique identifier for each customer."
        tests:
            - unique
            - not_null

  - name: stg_localbike_dataset__order_items
    description: "This model contains information about each item included in an order, including its price, quantity, and discount."
    columns:
      - name: order_item_id
        description: "Primary key, unique identifier for each order item: generated by concatenating order_id and item_id."
        tests:
            - unique
            - not_null
      - name: order_id
        description: "Foreign key linking the order item to the corresponding order."
        tests:
          - relationships:
              name: order_id_foreign_key_in_stg_localbike_dataset__order_items
              to: ref('stg_localbike_dataset__orders')
              field: order_id
      - name: product_id
        description: "Foreign key linking the order item to the corresponding product."
        tests:
          - relationships:
              name: product_id_foreign_key_in_stg_localbike_dataset__order_items
              to: ref('stg_localbike_dataset__products')
              field: product_id
      - name: total_order_item_amount
        description: "The total amount for this order item, calculated as (price * quantity * (1-discount))."

  - name: stg_localbike_dataset__orders
    description: "This model contains information about orders placed by customers, including the status of each order."
    columns:
      - name: order_id
        description: "Primary key, unique identifier for each order."
        tests:
            - unique
            - not_null
      - name: customer_id
        description: "Foreign key linking the order to the customer who placed it."
        tests:
          - relationships:
              name: customer_id_foreign_key_in_stg_localbike_dataset__orders
              to: ref('stg_localbike_dataset__customers')
              field: customer_id
      - name: store_id
        description: "Foreign key linking the order to the store in which it was placed."
        tests:
          - relationships:
              name: store_id_foreign_key_in_stg_localbike_dataset__orders
              to: ref('stg_localbike_dataset__stores')
              field: store_id
      - name: staff_id
        description: "Foreign key linking the order to the staff who processed it."
        tests:
          - relationships:
              name: staff_id_foreign_key_in_stg_localbike_dataset__orders
              to: ref('stg_localbike_dataset__staffs')
              field: staff_id

  - name: stg_localbike_dataset__products
    description: "This model contains details of products available for sale, primarily focusing on information about the product's brand, category, year of the model and price."
    columns:
      - name: product_id
        description: "Primary key, unique identifier for each product."
        tests:
            - unique
            - not_null
      - name: brand_id
        description: "Foreign key linking the product to its brand."
        tests:
          - relationships:
              name: brand_id_foreign_key_in_stg_localbike_dataset__products
              to: ref('stg_localbike_dataset__brands')
              field: brand_id
      - name: category_id
        description: "Foreign key linking the product to its category."
        tests:
          - relationships:
              name: category_id_foreign_key_in_stg_localbike_dataset__products
              to: ref('stg_localbike_dataset__categories')
              field: category_id

  - name: stg_localbike_dataset__staffs
    description: "This model contains staff-related information, including the store in which they work."
    columns:
      - name: staff_id
        description: "Primary key, unique identifier for each member of staff."
        tests:
            - unique
            - not_null
      - name: store_id
        description: "Foreign key linking the staff to their store."
        tests:
          - relationships:
              name: store_id_foreign_key_in_stg_localbike_dataset__staffs
              to: ref('stg_localbike_dataset__stores')
              field: store_id

  - name: stg_localbike_dataset__stocks
    description: "This model contains stock-related information, including store, product and quantity."
    columns:
      - name: stock_id
        description: "Primary key, unique identifier for each stock item: generated by concatenating store_id and product_id."
        tests:
            - unique
            - not_null
      - name: store_id
        description: "Foreign key linking the stock to its store."
        tests:
          - relationships:
              name: store_id_foreign_key_in_stg_localbike_dataset__stocks
              to: ref('stg_localbike_dataset__stores')
              field: store_id
      - name: product_id
        description: "Foreign key linking the stock to the corresponding product."
        tests:
          - relationships:
              name: product_id_foreign_key_in_stg_localbike_dataset__stocks
              to: ref('stg_localbike_dataset__products')
              field: product_id

  - name: stg_localbike_dataset__stores
    description: "This model contains store-related information, including their name and location."
    columns:
      - name: store_id
        description: "Primary key, unique identifier for each store."
        tests:
            - unique
            - not_null